FROM python:3.12-slim

RUN groupadd --system -g 1001 appgroup && useradd --system --uid 1001 -g 1001 appuser

WORKDIR /app

COPY app.py . 

RUN  chown appuser:appgroup app.py

USER appuser

EXPOSE 8080

ENTRYPOINT [ "python", "app.py" ]