FROM python:3.12-slim

RUN groupadd --system -g 1001 appgroup && useradd --system --uid 1001 -g 1001 appuser

WORKDIR /app

COPY app.py . 

RUN  chown appuser:appgroup app.py

USER appuser

HEALTHCHECK --interval=60s --timeout=3s --start-period=5s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:8080/ || exit 1

EXPOSE 8080

ENTRYPOINT [ "python", "app.py" ]